<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Web\Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="shapes.ttl" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dotNetRdf.Core" />
    <PackageReference Include="dotNetRdf.Shacl" />
  </ItemGroup>

</Project>
