<Project Sdk="MSTest.Sdk/4.4.1">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentAssertions.Web.v8" />
    <PackageReference Include="Testcontainers" />
  </ItemGroup>

</Project>
