<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.*" />
  </ItemGroup>

  <Target Name="ValidateEndpointDefinitions" AfterTargets="Publish">
    <Exec Command="dotnet run --project '$(MSBuildThisFileDirectory)../ValidateResources/ValidateResources.csproj' --configuration $(Configuration)" />
  </Target>

</Project>
